

const FETCH_REQUEST = "FETCH_REQUEST"
const FETCH_SUCCESS= "FETCH_SUCCESS"
let FETCH_FAILURE = "FETCH_FAILURE"


//Cart actiontype below
const ADD_PRODUCT ="ADD_PRODUCT"

const INCREASE_QUANTITY ="INCREASE_QUANTITY"
const DECREASE_QUANTITY ="DECREASE_QUANTITY"
const DELETE_ITEM = "DELETE_ITEM"
const CART_TOTAL = "CART_TOTAL"

//clear the cart
const CLEAR_CART = "CLEAR_CART"
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT"


export {FETCH_FAILURE,FETCH_REQUEST,FETCH_SUCCESS,ADD_PRODUCT,INCREASE_QUANTITY,DECREASE_QUANTITY,DELETE_ITEM, CART_TOTAL,CLEAR_CART}
